version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/react-app

permissions:
  - object: /home/ubuntu/react-app
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - directory
      - file
