version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/movix

permissions:
  - object: /home/ubuntu/movix
    owner: ubuntu
    group: ubuntu
    mode: 775
    type:
      - directory
      - file
