version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Building React app...
      - npm run build
      - echo Copying build files...
      - cp -r build/ ./  # move build content up if needed

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - build/**/*
  discard-paths: no
