version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Movix

hooks:
  AfterInstall:
    - runas: root
      timeout: 60
      command: |
        systemctl stop node.service || true
        systemctl daemon-reexec
        systemctl daemon-reload
        systemctl start node.service
        systemctl enable node.service


