name: React CI CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  build:
    name: Build React Application
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Verify build
        run: |
          test -d dist
          echo "React build completed successfully."


  Staging:
      name: Staging Deployment
      needs: build
  
      runs-on: ubuntu-latest
  
      environment:
        name: production
  
      steps:
  
        - name: Staging deployment started
          run: |
            echo "Production deployment approved."
            echo "This is where deployment commands will run."

          
  production:
    name: Production Deployment
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: production

    steps:

      - name: Production deployment started
        run: |
          echo "Production deployment approved."
          echo "This is where deployment commands will run."

      - name: Restart Nginx
        run: |
          echo "Nginx restart command will run here."
          echo "Currently running in test mode because no production server is connected."

      - name: Deployment completed
        run: |
          echo "Production deployment completed successfully."
